################################################################################
# statsd implementation
################################################################################

[StatsdInput]
address = "localhost:8128"

[StatAccumInput]
ticker_interval = 10
emit_in_payload = true

[CarbonOutput]
message_matcher = "Type == 'heka.statmetric' || (Type == 'heka.sandbox-output' && Fields[payload_type] == 'heka.statmetric')"
address = "localhost:2008"

################################################################################
# debug logging
################################################################################

[PayloadEncoder]

[LogOutput]
message_matcher = "TRUE"
encoder = "PayloadEncoder"
